---
baseurl: "http://www.randomthink.net/"
title: "RandomThink.net"
languageCode: "en-us"
metaDataFormat: "yaml"
permalinks:
params:
  author: "Brian Arnold"
  username: "brianarn"
  blog: /:year/:month/:title/
