---
baseurl: "http://www.randomthink.net/"
title: "RandomThink.net"

languageCode: "en-us"
metaDataFormat: "yaml"

params:
  author: "Brian Arnold"
  twitter: "brianarn"
  github: "brianarn"
  googleAnalytics: "UA-279164-1"

permalinks:
  blog: /blog/:year/:month/:title/
